### PR TITLE
remove hardcoded verbose 3 parameter

### PR DESCRIPTION
**Pull request by curcuz**
this is now supported as a dynamic parameter by openocd (`-d` from CLI and `debug_level` from telnet client) so there is no need to have it hardcoded. Plus, when set to 3 it floods stdout with quite the logstream using a non marginal chunk of CPU and FS I/O

### CODE REVIEW

**Comment by curcuz** [comment]
@balena-ci retest

**Comment by curcuz** [comment]
@balena-ci retest

**Comment by Bucknalla** [comment]
Sounds fine to me @curcuz anything extra needed in this or just for an approval?

**Comment by curcuz** [comment]
@Bucknalla just approval :)

**Review by Bucknalla — APPROVED** [review]
lgtm

**Pull request merged**
